module SteepPlayground
  module SafeOperator
    class Klass
      attr_reader num: Integer

      def initialize: (Integer) -> void
      def right: () -> Klass?
      def left:  () -> Klass?
    end
  end
end
